### ISSUE TITLE
Fixing image on mobile and improve css

### ISSUE THREAD

**Issue by karlosvas** [ignacionr/academy#2]
![Sin nombre](https://github.com/user-attachments/assets/1d5e1559-acb5-48e1-84c8-37c1b274265d)

When opening the website from a mobile device the image appears stretched, so it looks very bad visually, you should add in the "img" tag, the attribute style="object-fit: contain;".

Also as a personal recommendation I would tell you to add a footer, the main tag, which should wrap all the content that is not the footer, and a "margin-top: 50px;" to all the "h2"

**Comment by ignacionr** [comment]
Excellent stuff, much appreciated!
